---
name: "♻️ Trunk Call"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]

jobs:
  check-call:
    name: "♻️ Trunk"
    uses: z-shell/.github/.github/workflows/trunk-call.yml@main
    #    secrets:
    #      TRUNK_TOKEN: ${{ secrets.TRUNK_TOKEN }}
    with:
      arguments: --ci-progress
